# Lab 2.1 - ESO SecretStore
# Kết nối ESO với AWS Secrets Manager tại region us-east-1
# AWS credentials được đọc từ K8s Secret "aws-creds" (tạo bằng kubectl, KHÔNG commit)
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: aws-secrets-manager
  namespace: demo
spec:
  provider:
    aws:
      service: SecretsManager
      region: us-east-1
      auth:
        secretRef:
          accessKeyIDSecretRef:
            name: aws-creds
            key: access-key
          secretAccessKeySecretRef:
            name: aws-creds
            key: secret-key
