# Test F-04: Pod chạy root -> phải bị REJECT
apiVersion: v1
kind: Pod
metadata:
  name: test-root
  namespace: demo
spec:
  containers:
  - name: nginx
    image: nginx:1.25.0
    securityContext:
      runAsUser: 0
    resources:
      limits:
        cpu: 100m
        memory: 128Mi
